[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiosqlite>=0.21.0",
    "psutil>=7.0.0",
    "pyrogram>=2.0.106",
    "tgcrypto>=1.2.5",
]
